CREATE TABLE ENCRYPTED_TAB(
	ENCRP_ID INTEGER(6) NOT NULL AUTO_INCREMENT,
	ENCRYPTED_MSG VARCHAR(300) NOT NULL,
	
PRIMARY KEY (ENCRP_ID)
);

CREATE TABLE DECRYPTED_TAB(
	DECRP_ID INTEGER(6) NOT NULL AUTO_INCREMENT,
	DECRYPTED_MSG VARCHAR(300) NOT NULL,
	PRIMARY KEY (DECRP_ID),
	ENCRP_ID INTEGER(6) CONSTRAINT FK_ENCRP_ID REFERENCES ENCRYPTED_TAB
);

--ALTER TABLE ENCRYPTED_TAB set AUTO_INCREMENT = 101;
