package com.techleads.app.common;

public interface DBQueries {
	// USER SERVICE QUERIES
	String SELECT_ALL_MSGS = "SELECT ENCRP_ID, ENCRYPTED_MSG FROM ENCRYPTED_TAB";
	String SELECT_MSGS_BY_ID = "SELECT ENCRP_ID, ENCRYPTED_MSG FROM ENCRYPTED_TAB WHERE ENCRP_ID=?";
	
	String SELECT_MSGS_BY_MAX_ID = "SELECT ENCRP_ID, ENCRYPTED_MSG FROM ENCRYPTED_TAB WHERE ENCRP_ID=(SELECT MAX(ENCRP_ID)  FROM ENCRYPTED_TAB)";
	

	String INSERT_INTO_ENCRYPTED_TAB = "INSERT INTO ENCRYPTED_TAB (ENCRYPTED_MSG) VALUES(?)";
	
	String INSERT_INTO_DECRYPTED_TAB = "INSERT INTO DECRYPTED_TAB (DECRYPTED_MSG, ENCRP_ID) VALUES(?, ?)";

	String UPDATE_USER_BY_ID = "UPDATE USERS SET LOCATION=?, CARDTYPE=?, CARDNUMBER=?, CVVNUMBER=? WHERE USER_ID=?";
	String DELETE_ENCRYPTED_TAB_BY_ID = "DELETE FROM ENCRYPTED_TAB WHERE ENCRP_ID=?";

	
}


