package com.techleads.app.common;

public interface DBQueries {
	// USER SERVICE QUERIES
	String SELECT_ALL_MSGS = "SELECT ENCRP_ID, ENCRYPTED_MSG FROM ENCRYPTED_TAB";
	String SELECT_MSGS_BY_ID = "SELECT ENCRP_ID, ENCRYPTED_MSG FROM ENCRYPTED_TAB WHERE ENCRP_ID=?";

	String SELECT_MSGS_BY_MAX_ID = "SELECT ENCRP_ID, ENCRYPTED_MSG FROM ENCRYPTED_TAB WHERE ENCRP_ID=(SELECT MAX(ENCRP_ID)  FROM ENCRYPTED_TAB)";

	String INSERT_INTO_ENCRYPTED_TAB = "INSERT INTO ENCRYPTED_TAB (ENCRYPTED_MSG) VALUES(?)";

	String INSERT_INTO_DECRYPTED_TAB = "INSERT INTO DECRYPTED_TAB (DECRYPTED_MSG, ENCRP_ID) VALUES(?, ?)";

//	String SELECT_DECRYPT_MSG_BY_ENCRYPT_AND_ID = "SELECT E.ENCRP_ID, E.ENCRYPTED_MSG, D.DECRYPTED_MSG FROM ENCRYPTED_TAB E INNER JOIN DECRYPTED_TAB D ON E.ENCRP_ID = D.DECRP_ID WHERE E.ENCRP_ID=? AND ENCRYPTED_MSG=?";

	String UPDATE_USER_BY_ID = "UPDATE USERS SET LOCATION=?, CARDTYPE=?, CARDNUMBER=?, CVVNUMBER=? WHERE USER_ID=?";
	String DELETE_ENCRYPTED_TAB_BY_ID = "DELETE FROM ENCRYPTED_TAB WHERE ENCRP_ID=?";
	
	
	String SELECT_DECRYPT_MSG_BY_ENCRYPT_AND_ID = "	SELECT E.ENCRP_ID , E.ENCRYPTED_MSG, D.DECRYPTED_MSG  FROM  ENCRYPTED_TAB E\r\n"
	+ "	INNER JOIN "
	+ "	DECRYPTED_TAB D "
	+ "	ON E.ENCRP_ID =D.ENCRP_ID "
	+ "	WHERE E.ENCRP_ID =? "
	+ "	AND "
	+ "	ENCRYPTED_MSG =?";

}
